# 05_image-streams.yaml
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: risk-assessment
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/yogendra/xraylab-risk-assessment:v1.0.3'
      importPolicy: {}
      referencePolicy:
        type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: image-generator
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/yogendra/xraylab-image-generator:v2.0'
      importPolicy: {}
      referencePolicy:
        type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: image-server
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/yogendra/xraylab-image-server:v2.0'
      importPolicy: {}
      referencePolicy:
        type: Source
